BEGIN;
--
-- Create model MedSpa
--
CREATE TABLE "api_medspa" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "address" varchar(255) NOT NULL, "phone_number" varchar(20) NOT NULL, "email" varchar(254) NOT NULL UNIQUE);
--
-- Create model Appointment
--
CREATE TABLE "api_appointment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "start_time" timestamp with time zone NOT NULL, "status" varchar(20) NOT NULL, "total_duration" integer NOT NULL CHECK ("total_duration" >= 0), "total_price" numeric(10, 2) NULL, "med_spa_id" bigint NOT NULL);
--
-- Create model Service
--
CREATE TABLE "api_service" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "description" text NOT NULL, "price" numeric(10, 2) NOT NULL, "duration" integer NOT NULL CHECK ("duration" >= 0), "med_spa_id" bigint NOT NULL);
--
-- Create model AppointmentServiceRel
--
CREATE TABLE "api_appointmentservicerel" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "appointment_id" bigint NOT NULL, "service_id" bigint NOT NULL);
--
-- Add field services to appointment
--
-- (no-op)
CREATE INDEX "api_medspa_email_fcf753ed_like" ON "api_medspa" ("email" varchar_pattern_ops);
ALTER TABLE "api_appointment" ADD CONSTRAINT "api_appointment_med_spa_id_d12be03d_fk_api_medspa_id" FOREIGN KEY ("med_spa_id") REFERENCES "api_medspa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_appointment_med_spa_id_d12be03d" ON "api_appointment" ("med_spa_id");
ALTER TABLE "api_service" ADD CONSTRAINT "api_service_med_spa_id_a5ceceb7_fk_api_medspa_id" FOREIGN KEY ("med_spa_id") REFERENCES "api_medspa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_service_med_spa_id_a5ceceb7" ON "api_service" ("med_spa_id");
ALTER TABLE "api_appointmentservicerel" ADD CONSTRAINT "api_appointmentservicere_appointment_id_service_i_e336dfc0_uniq" UNIQUE ("appointment_id", "service_id");
ALTER TABLE "api_appointmentservicerel" ADD CONSTRAINT "api_appointmentservi_appointment_id_d02ba797_fk_api_appoi" FOREIGN KEY ("appointment_id") REFERENCES "api_appointment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_appointmentservicerel" ADD CONSTRAINT "api_appointmentservicerel_service_id_a71925e0_fk_api_service_id" FOREIGN KEY ("service_id") REFERENCES "api_service" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_appointmentservicerel_appointment_id_d02ba797" ON "api_appointmentservicerel" ("appointment_id");
CREATE INDEX "api_appointmentservicerel_service_id_a71925e0" ON "api_appointmentservicerel" ("service_id");
COMMIT;
