#!/bin/bash

# List of service products
service_products=(
    "Botox"
    "Daxxify"
    "Dysport"
    "Jeuveau"
    "Xeomin"
    "Juvederm Ultra XC"
    "Juvederm Ultra Plus XC"
    "Juvederm Volbella"
    "Juvederm Vollure"
    "Juvederm Voluma"
    "Juvederm Volux"
    "Juvederm Skinvive"
    "Restylane"
    "Restylane-L"
    "Restylane Contour"
    "Restylane Defyne"
    "Restylane Eyelight"
    "Restylane Kysse"
    "Restylane Lyft"
    "Restylane Silk"
    "Restylane Refyne"
    "RHA 2"
    "RHA 3"
    "RHA 4"
    "RHA Redensity"
    "Revanesse Lips"
    "Revanesse Versa"
    "Belotero Balance"
    "Radiesse"
    "Hyperdilute Radiesse"
    "Hylanex"
    "Bellafill"
    "Sculptra"
    "PRX"
    "VI Peel: Classic Precision Plus"
    "SkinMedica: Illuminze"
    "SkinMedica: Rejuvenize"
    "SkinMedica: Vitalize"
    "ZO Skin Health: 3 step peel"
    "Perfect DermaPeel"
    "TCA"
    "Other Chemical Peel Product"
    "Kybella"
    "Asclera"
    "Smooth PDO Threads"
    "Lifting PDO Threads"
    "Barbed/Cones PDO Threads"
    "Trizepatide"
    "Phentermine"
    "Liraglutide"
    "Semaglutide"
    "B Vitamins"
    "Vitamin C"
    "Arginine"
    "Ornithine"
    "Lysine"
    "Carnitine"
    "Ascorbic Acid"
    "Biotin"
    "Manganese"
    "Copper"
    "Magnesium Chloride"
    "Calcium Chloride"
    "NAD"
    "Zinc"
    "Glutathione"
    "B-12"
    "MIC"
    "Ipamorelin"
    "CJC"
    "BPC 157"
)

# Loop through service products and create ServiceProduct instances
for product in "${service_products[@]}"; do
    python manage.py shell -c "from api.models import ServiceProduct; ServiceProduct.objects.create(name='$product')"
done
